---
- include: prepare_environment.yml

- include: generate_manifest.yml
  when: moodle_manifest == None

- include: fetch_git_manifest.yml
  when: moodle_manifest.type is defined and moodle_manifest.type == 'git'

- include: fetch_zip_manifest.yml
  when: moodle_manifest.type is defined and moodle_manifest.type == 'zip'
  
# Assemble moodle
- name: Assemble moodle source code
  command: "{{ moodle_pytasc_executable }} 
    --manifest={{ moodle_config_dir }}/manifest.yml 
    --destination={{ moodle_location }}
    {% if moodle_tasc_extra_params %}
      --extra-parameters='{{ '{' }}{% for param in moodle_tasc_extra_params %}\"{{ param.name }}\":\"{{ param.value }}\"{% endfor %}{{ '}' }}'
    {% endif %}"
