---
# Install prerequisites
- include: prerequisites.yml

# Assemble Moodle
- include: assemble.yml
  when: moodle_install_method != 'local'

# Configure Moodle
- include: configure.yml
  when: moodle_assemble_only

# Install Moodle
- include: install.yml
  when: moodle_assemble_only == false

# Copy dev plugins to Moodle
- include: plugin_dev.yml
  when: moodle_plugins_dev|length > 0
