---
- name: Create custom plugin directories
  file: 
    path: "{{ moodle_location }}/{{ item.destination }}/{{ item.shortname }}"
    state: directory
  with_items: "{{ moodle_plugins_dev }}"
  
- name: Write rsync script to synchronize plugins
  template: src=rsync_plugins.sh.j2 dest=~/rsync_plugins.sh
  
- name: Determine if the rsync script is running
  shell: "ps ax | grep [r]sync_plugins"
  register: rsync_running
  failed_when: "'FAILED' in rsync_running.stdout"
  
- name: Make sure the sync script starts on startup
  lineinfile:
    line: /bin/bash /root/rsync_plugins.sh &
    insertbefore: "exit 0"
    dest: /etc/rc.local
  
- name: Run rsync script to synchronize plugins
  shell: /bin/bash ~/rsync_plugins.sh &
  async: 5
  poll: 0
  when: rsync_running.rc == 1
